/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GestoriaRouteImport } from './routes/gestoria'
import { Route as SegurosRouteImport } from './routes/seguros'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as CatalogoIndexRouteImport } from './routes/catalogo.index'
import { Route as CatalogoSlugRouteImport } from './routes/catalogo.$slug'
import { Route as AdminVehiculosIdRouteImport } from './routes/admin/vehiculos.$id'
import { Route as AdminVehiculosNuevoRouteImport } from './routes/admin/vehiculos.nuevo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GestoriaRoute = GestoriaRouteImport.update({
  id: '/gestoria',
  path: '/gestoria',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurosRoute = SegurosRouteImport.update({
  id: '/seguros',
  path: '/seguros',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoIndexRoute = CatalogoIndexRouteImport.update({
  id: '/catalogo/',
  path: '/catalogo/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoSlugRoute = CatalogoSlugRouteImport.update({
  id: '/catalogo/$slug',
  path: '/catalogo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVehiculosIdRoute = AdminVehiculosIdRouteImport.update({
  id: '/admin/vehiculos/$id',
  path: '/admin/vehiculos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVehiculosNuevoRoute = AdminVehiculosNuevoRouteImport.update({
  id: '/admin/vehiculos/nuevo',
  path: '/admin/vehiculos/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gestoria': typeof GestoriaRoute
  '/seguros': typeof SegurosRoute
  '/admin/login': typeof AdminLoginRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/catalogo/': typeof CatalogoIndexRoute
  '/admin/vehiculos/$id': typeof AdminVehiculosIdRoute
  '/admin/vehiculos/nuevo': typeof AdminVehiculosNuevoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gestoria': typeof GestoriaRoute
  '/seguros': typeof SegurosRoute
  '/admin/login': typeof AdminLoginRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/catalogo': typeof CatalogoIndexRoute
  '/admin/vehiculos/$id': typeof AdminVehiculosIdRoute
  '/admin/vehiculos/nuevo': typeof AdminVehiculosNuevoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gestoria': typeof GestoriaRoute
  '/seguros': typeof SegurosRoute
  '/admin/login': typeof AdminLoginRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/catalogo/': typeof CatalogoIndexRoute
  '/admin/vehiculos/$id': typeof AdminVehiculosIdRoute
  '/admin/vehiculos/nuevo': typeof AdminVehiculosNuevoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gestoria'
    | '/seguros'
    | '/admin/login'
    | '/catalogo/$slug'
    | '/admin/'
    | '/catalogo/'
    | '/admin/vehiculos/$id'
    | '/admin/vehiculos/nuevo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gestoria'
    | '/seguros'
    | '/admin/login'
    | '/catalogo/$slug'
    | '/admin'
    | '/catalogo'
    | '/admin/vehiculos/$id'
    | '/admin/vehiculos/nuevo'
  id:
    | '__root__'
    | '/'
    | '/gestoria'
    | '/seguros'
    | '/admin/login'
    | '/catalogo/$slug'
    | '/admin/'
    | '/catalogo/'
    | '/admin/vehiculos/$id'
    | '/admin/vehiculos/nuevo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GestoriaRoute: typeof GestoriaRoute
  SegurosRoute: typeof SegurosRoute
  AdminLoginRoute: typeof AdminLoginRoute
  CatalogoSlugRoute: typeof CatalogoSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CatalogoIndexRoute: typeof CatalogoIndexRoute
  AdminVehiculosIdRoute: typeof AdminVehiculosIdRoute
  AdminVehiculosNuevoRoute: typeof AdminVehiculosNuevoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestoria': {
      id: '/gestoria'
      path: '/gestoria'
      fullPath: '/gestoria'
      preLoaderRoute: typeof GestoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguros': {
      id: '/seguros'
      path: '/seguros'
      fullPath: '/seguros'
      preLoaderRoute: typeof SegurosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/': {
      id: '/catalogo/'
      path: '/catalogo'
      fullPath: '/catalogo/'
      preLoaderRoute: typeof CatalogoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/$slug': {
      id: '/catalogo/$slug'
      path: '/catalogo/$slug'
      fullPath: '/catalogo/$slug'
      preLoaderRoute: typeof CatalogoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vehiculos/$id': {
      id: '/admin/vehiculos/$id'
      path: '/admin/vehiculos/$id'
      fullPath: '/admin/vehiculos/$id'
      preLoaderRoute: typeof AdminVehiculosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vehiculos/nuevo': {
      id: '/admin/vehiculos/nuevo'
      path: '/admin/vehiculos/nuevo'
      fullPath: '/admin/vehiculos/nuevo'
      preLoaderRoute: typeof AdminVehiculosNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GestoriaRoute: GestoriaRoute,
  SegurosRoute: SegurosRoute,
  AdminLoginRoute: AdminLoginRoute,
  CatalogoSlugRoute: CatalogoSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  CatalogoIndexRoute: CatalogoIndexRoute,
  AdminVehiculosIdRoute: AdminVehiculosIdRoute,
  AdminVehiculosNuevoRoute: AdminVehiculosNuevoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
